// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: secret/emergencybutton/v1beta1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgToggleIbcSwitch represents a message to toggle the emergencybutton status
// by the defined pauser.
type MsgToggleIbcSwitch struct {
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
}

func (m *MsgToggleIbcSwitch) Reset()         { *m = MsgToggleIbcSwitch{} }
func (m *MsgToggleIbcSwitch) String() string { return proto.CompactTextString(m) }
func (*MsgToggleIbcSwitch) ProtoMessage()    {}
func (*MsgToggleIbcSwitch) Descriptor() ([]byte, []int) {
	return fileDescriptor_72649c7fc51bf646, []int{0}
}
func (m *MsgToggleIbcSwitch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgToggleIbcSwitch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgToggleIbcSwitch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgToggleIbcSwitch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgToggleIbcSwitch.Merge(m, src)
}
func (m *MsgToggleIbcSwitch) XXX_Size() int {
	return m.Size()
}
func (m *MsgToggleIbcSwitch) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgToggleIbcSwitch.DiscardUnknown(m)
}

var xxx_messageInfo_MsgToggleIbcSwitch proto.InternalMessageInfo

func (m *MsgToggleIbcSwitch) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

// MsgToggleIbcSwitchResponse defines the response type for the toggle.
type MsgToggleIbcSwitchResponse struct {
}

func (m *MsgToggleIbcSwitchResponse) Reset()         { *m = MsgToggleIbcSwitchResponse{} }
func (m *MsgToggleIbcSwitchResponse) String() string { return proto.CompactTextString(m) }
func (*MsgToggleIbcSwitchResponse) ProtoMessage()    {}
func (*MsgToggleIbcSwitchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_72649c7fc51bf646, []int{1}
}
func (m *MsgToggleIbcSwitchResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgToggleIbcSwitchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgToggleIbcSwitchResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgToggleIbcSwitchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgToggleIbcSwitchResponse.Merge(m, src)
}
func (m *MsgToggleIbcSwitchResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgToggleIbcSwitchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgToggleIbcSwitchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgToggleIbcSwitchResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgToggleIbcSwitch)(nil), "secret.emergencybutton.v1beta1.MsgToggleIbcSwitch")
	proto.RegisterType((*MsgToggleIbcSwitchResponse)(nil), "secret.emergencybutton.v1beta1.MsgToggleIbcSwitchResponse")
}

func init() {
	proto.RegisterFile("secret/emergencybutton/v1beta1/tx.proto", fileDescriptor_72649c7fc51bf646)
}

var fileDescriptor_72649c7fc51bf646 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2f, 0x4e, 0x4d, 0x2e,
	0x4a, 0x2d, 0xd1, 0x4f, 0xcd, 0x4d, 0x2d, 0x4a, 0x4f, 0xcd, 0x4b, 0xae, 0x4c, 0x2a, 0x2d, 0x29,
	0xc9, 0xcf, 0xd3, 0x2f, 0x33, 0x4c, 0x4a, 0x2d, 0x49, 0x34, 0xd4, 0x2f, 0xa9, 0xd0, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x92, 0x83, 0x28, 0xd4, 0x43, 0x53, 0xa8, 0x07, 0x55, 0x28, 0x25, 0x92,
	0x9e, 0x9f, 0x9e, 0x0f, 0x56, 0xaa, 0x0f, 0x62, 0x41, 0x74, 0x29, 0xe9, 0x70, 0x09, 0xf9, 0x16,
	0xa7, 0x87, 0xe4, 0xa7, 0xa7, 0xe7, 0xa4, 0x7a, 0x26, 0x25, 0x07, 0x97, 0x67, 0x96, 0x24, 0x67,
	0x08, 0x89, 0x71, 0xb1, 0x15, 0xa7, 0xe6, 0xa5, 0xa4, 0x16, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70,
	0x06, 0x41, 0x79, 0x4a, 0x32, 0x5c, 0x52, 0x98, 0xaa, 0x83, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a,
	0x53, 0x8d, 0x3a, 0x19, 0xb9, 0x98, 0x7d, 0x8b, 0xd3, 0x85, 0x1a, 0x19, 0xb9, 0xf8, 0xd1, 0x4d,
	0x34, 0xd2, 0xc3, 0xef, 0x3c, 0x3d, 0x4c, 0x73, 0xa5, 0xac, 0x48, 0xd7, 0x03, 0x73, 0x8b, 0x53,
	0xf0, 0x89, 0x47, 0x72, 0x8c, 0x17, 0x1e, 0xc9, 0x31, 0x3e, 0x78, 0x24, 0xc7, 0x38, 0xe1, 0xb1,
	0x1c, 0xc3, 0x85, 0xc7, 0x72, 0x0c, 0x37, 0x1e, 0xcb, 0x31, 0x44, 0x59, 0xa6, 0x67, 0x96, 0x64,
	0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x17, 0x27, 0x17, 0x95, 0xe4, 0x24, 0x26, 0x15, 0xeb,
	0x07, 0x83, 0x2d, 0xf2, 0x4b, 0x2d, 0x29, 0xcf, 0x2f, 0xca, 0xd6, 0xaf, 0xc0, 0x08, 0xed, 0x92,
	0xca, 0x82, 0xd4, 0xe2, 0x24, 0x36, 0x70, 0x98, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xec,
	0x39, 0x98, 0x80, 0x94, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// ToggleIbcSwitch defines a method for toggling the status of the
	// emergencybutton.
	ToggleIbcSwitch(ctx context.Context, in *MsgToggleIbcSwitch, opts ...grpc.CallOption) (*MsgToggleIbcSwitchResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ToggleIbcSwitch(ctx context.Context, in *MsgToggleIbcSwitch, opts ...grpc.CallOption) (*MsgToggleIbcSwitchResponse, error) {
	out := new(MsgToggleIbcSwitchResponse)
	err := c.cc.Invoke(ctx, "/secret.emergencybutton.v1beta1.Msg/ToggleIbcSwitch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// ToggleIbcSwitch defines a method for toggling the status of the
	// emergencybutton.
	ToggleIbcSwitch(context.Context, *MsgToggleIbcSwitch) (*MsgToggleIbcSwitchResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ToggleIbcSwitch(ctx context.Context, req *MsgToggleIbcSwitch) (*MsgToggleIbcSwitchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToggleIbcSwitch not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ToggleIbcSwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgToggleIbcSwitch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ToggleIbcSwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/secret.emergencybutton.v1beta1.Msg/ToggleIbcSwitch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ToggleIbcSwitch(ctx, req.(*MsgToggleIbcSwitch))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "secret.emergencybutton.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ToggleIbcSwitch",
			Handler:    _Msg_ToggleIbcSwitch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "secret/emergencybutton/v1beta1/tx.proto",
}

func (m *MsgToggleIbcSwitch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgToggleIbcSwitch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgToggleIbcSwitch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgToggleIbcSwitchResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgToggleIbcSwitchResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgToggleIbcSwitchResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgToggleIbcSwitch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgToggleIbcSwitchResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgToggleIbcSwitch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgToggleIbcSwitch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgToggleIbcSwitch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgToggleIbcSwitchResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgToggleIbcSwitchResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgToggleIbcSwitchResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
