[package]
name = "mint"
version = "0.9.0-alpha1"
authors = ["Cash Maney <itzik@enigma.co>"]
publish = false
edition = "2018"
description = "Reflect messages to use for test cases - based on cw-mask"
license = "Apache-2.0"
exclude = [
  # Those files are cosmwasm-opt artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
default = []

[dependencies]
cosmwasm-std = { package = "secret-cosmwasm-std", version = "0.10.1"}
cosmwasm-storage = { package = "secret-cosmwasm-storage", version = "0.10.0" }
schemars = "0.7"
serde = { version = "=1.0.103", default-features = false, features = [
  "derive"
] }
