// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: secret/ibc-switch/v1beta1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState - genesis state of x/wasm
type GenesisState struct {
	// Params params = 1 [(gogoproto.nullable) = false];
	SwitchStatus  string `protobuf:"bytes,1,opt,name=switch_status,json=switchStatus,proto3" json:"switch_status,omitempty"`
	PauserAddress string `protobuf:"bytes,2,opt,name=pauser_address,json=pauserAddress,proto3" json:"pauser_address,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbe5535a7c664437, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetSwitchStatus() string {
	if m != nil {
		return m.SwitchStatus
	}
	return ""
}

func (m *GenesisState) GetPauserAddress() string {
	if m != nil {
		return m.PauserAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "secret.ibcswitch.v1beta1.GenesisState")
}

func init() {
	proto.RegisterFile("secret/ibc-switch/v1beta1/genesis.proto", fileDescriptor_fbe5535a7c664437)
}

var fileDescriptor_fbe5535a7c664437 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x63, 0x06, 0x24, 0xa2, 0x96, 0x21, 0x42, 0x22, 0x02, 0xe4, 0x22, 0x16, 0x18, 0x20,
	0x56, 0x05, 0x0f, 0x00, 0x65, 0x60, 0xeb, 0x40, 0x36, 0x96, 0xca, 0x76, 0x4f, 0xa9, 0x05, 0xc1,
	0x96, 0xef, 0x42, 0xe9, 0x5b, 0xb0, 0xf0, 0x4e, 0x8c, 0x1d, 0x99, 0x2a, 0x94, 0x6c, 0x7d, 0x0a,
	0x84, 0xcd, 0xd0, 0x6e, 0xa7, 0xfb, 0xbe, 0xfb, 0xa5, 0xff, 0xd2, 0x73, 0x04, 0xed, 0x81, 0x84,
	0x51, 0xfa, 0x0a, 0xe7, 0x86, 0xf4, 0x4c, 0xbc, 0x0d, 0x15, 0x90, 0x1c, 0x8a, 0x0a, 0x5e, 0x01,
	0x0d, 0x16, 0xce, 0x5b, 0xb2, 0x59, 0x1e, 0xc5, 0xc2, 0x28, 0x1d, 0xbd, 0xe2, 0xdf, 0x3b, 0x3a,
	0xa8, 0x6c, 0x65, 0x83, 0x24, 0xfe, 0xa6, 0xe8, 0x9f, 0x7d, 0xb2, 0xb4, 0xf7, 0x10, 0x13, 0x4a,
	0x92, 0x04, 0xd9, 0x6d, 0xda, 0x8f, 0x87, 0x13, 0x24, 0x49, 0x0d, 0xe6, 0xec, 0x94, 0x5d, 0xec,
	0x8d, 0x8e, 0xd7, 0xab, 0xc1, 0xe1, 0x16, 0xb8, 0xb4, 0xb5, 0x21, 0xa8, 0x1d, 0x2d, 0x1e, 0x7b,
	0x11, 0x94, 0x61, 0x9f, 0xdd, 0xa7, 0xfb, 0x4e, 0x36, 0x08, 0x7e, 0x22, 0xa7, 0x53, 0x0f, 0x88,
	0xf9, 0x4e, 0x88, 0x38, 0x59, 0xaf, 0x06, 0xf9, 0x36, 0xd9, 0xc8, 0xe8, 0x47, 0x72, 0x17, 0xc1,
	0x68, 0xfc, 0xd5, 0x72, 0xb6, 0x6c, 0x39, 0xfb, 0x69, 0x39, 0xfb, 0xe8, 0x78, 0xb2, 0xec, 0x78,
	0xf2, 0xdd, 0xf1, 0xe4, 0xe9, 0xa6, 0x32, 0x34, 0x6b, 0x54, 0xa1, 0x6d, 0x2d, 0x50, 0x7b, 0x7a,
	0x91, 0x0a, 0x45, 0x19, 0x5a, 0x8f, 0x81, 0xe6, 0xd6, 0x3f, 0x8b, 0xf7, 0xcd, 0x3f, 0xd1, 0xc2,
	0x01, 0xaa, 0xdd, 0x50, 0xf7, 0xfa, 0x37, 0x00, 0x00, 0xff, 0xff, 0x7e, 0xa6, 0x3e, 0x5b, 0x49,
	0x01, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PauserAddress) > 0 {
		i -= len(m.PauserAddress)
		copy(dAtA[i:], m.PauserAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.PauserAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SwitchStatus) > 0 {
		i -= len(m.SwitchStatus)
		copy(dAtA[i:], m.SwitchStatus)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.SwitchStatus)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SwitchStatus)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.PauserAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwitchStatus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SwitchStatus = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PauserAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PauserAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
