#!/bin/bash
# This `DEBIAN/postinst` script is run post-installation

set -e

cat <<EOF > /etc/systemd/system/secret-node.service
[Unit]
Description=Secret node service
After=network.target

[Service]
Type=simple
ExecStart=$(which secretd) start
User=$(logname)
Restart=on-failure
StartLimitInterval=0
RestartSec=3
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
EOF
sudo systemctl daemon-reload

sudo perl -i -pe 's/#SystemMaxUse=.*/SystemMaxUse=50M/' /etc/systemd/journald.conf
sudo systemctl restart systemd-journald
