#!/usr/bin/env bash
# This `DEBIAN/postinst` script is run post-installation

set -e

cat <<EOF > /etc/systemd/system/secret-node.service
[Unit]
Description=Secret node service
After=network.target

[Service]
Type=simple
Environment=SCRT_ENCLAVE_DIR=/usr/lib
WorkingDirectory=$(eval echo ~$(logname))
ExecStart=$(which secretd) start
User=$(logname)
Restart=on-failure
StartLimitInterval=0
RestartSec=3
LimitNOFILE=65535
LimitMEMLOCK=209715200

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload

mkdir -p "$(eval echo ~$(logname))/.sgx_secrets"
chown -R $(logname):$(logname) "$(eval echo ~$(logname))/.sgx_secrets"