[global]
log_level = 'info'

[mode]
[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true

[rest]
enabled = true
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'secretdev-1'
rpc_addr = 'http://localsecret-1:26657'
grpc_addr = 'http://localsecret-1:9090'
websocket_addr = 'ws://localsecret-1:26657/websocket'

rpc_timeout = '10s'
account_prefix = 'secret'
key_name = 'local1-alt'
store_prefix = 'ibc'
default_gas = 50000
max_gas = 2000000
gas_price = { price = 1, denom = 'uscrt' }
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '10s'
trusting_period = '79s'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }

[chains.packet_filter]
policy = 'allow'
list = [
    ['wasm.*', '*'],
    ['transfer', '*']
]

[[chains]]
id = 'secretdev-2'
rpc_addr = 'http://localsecret-2:26657'
grpc_addr = 'http://localsecret-2:9090'
websocket_addr = 'ws://localsecret-2:26657/websocket'

rpc_timeout = '10s'
account_prefix = 'secret'
key_name = 'local2-alt'
store_prefix = 'ibc'
default_gas = 50000
max_gas = 2000000
gas_price = { price = 1, denom = 'uscrt' }
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '10s'
trusting_period = '79s'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }

[chains.packet_filter]
policy = 'allow'
list = [
    ['wasm.*', '*'],
    ['transfer', '*']
]
