// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: secret/registration/v1beta1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GenesisState struct {
	Registration              []*RegistrationNodeInfo `protobuf:"bytes,1,rep,name=registration,proto3" json:"reg_info"`
	NodeExchMasterCertificate *MasterCertificate      `protobuf:"bytes,2,opt,name=node_exch_master_certificate,json=nodeExchMasterCertificate,proto3" json:"node_exch_cert"`
	IoMasterCertificate       *MasterCertificate      `protobuf:"bytes,3,opt,name=io_master_certificate,json=ioMasterCertificate,proto3" json:"io_exch_cert"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce4400b3c39a810a, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GenesisState)(nil), "secret.registration.v1beta1.GenesisState")
}

func init() {
	proto.RegisterFile("secret/registration/v1beta1/genesis.proto", fileDescriptor_ce4400b3c39a810a)
}

var fileDescriptor_ce4400b3c39a810a = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xc1, 0x4a, 0x02, 0x41,
	0x18, 0xc7, 0x77, 0x15, 0x22, 0xd6, 0x25, 0x62, 0x2b, 0x30, 0x8b, 0x51, 0x82, 0xc8, 0x2e, 0xbb,
	0x68, 0x2f, 0x10, 0x46, 0x44, 0x87, 0x3c, 0xe8, 0xad, 0xcb, 0x32, 0x3b, 0x7e, 0x8e, 0x43, 0xed,
	0x8c, 0xcc, 0x7e, 0x95, 0x9d, 0x7b, 0x81, 0x1e, 0xa3, 0x47, 0xf1, 0xe8, 0xb1, 0x93, 0xd4, 0x7a,
	0xf3, 0xd2, 0x2b, 0x84, 0xbb, 0x82, 0x2b, 0xc6, 0x1e, 0xba, 0xcd, 0x0c, 0xbf, 0xff, 0xef, 0xff,
	0xc1, 0x37, 0xd6, 0x79, 0x04, 0x4c, 0x03, 0x7a, 0x1a, 0xb8, 0x88, 0x50, 0x53, 0x14, 0x4a, 0x7a,
	0xcf, 0x8d, 0x00, 0x90, 0x36, 0x3c, 0x0e, 0x12, 0x22, 0x11, 0xb9, 0x43, 0xad, 0x50, 0x39, 0x47,
	0x29, 0xea, 0x66, 0x51, 0x77, 0x89, 0x56, 0xf6, 0xb9, 0xe2, 0x2a, 0xe1, 0xbc, 0xc5, 0x29, 0x8d,
	0x54, 0xce, 0xf2, 0xec, 0xf8, 0x3a, 0x84, 0xa5, 0xbb, 0x72, 0x9a, 0x07, 0x86, 0x11, 0x4f, 0xb1,
	0x93, 0x9f, 0x82, 0x65, 0xdf, 0xa4, 0x43, 0x75, 0x91, 0x22, 0x38, 0xcc, 0xb2, 0xb3, 0x91, 0xb2,
	0x59, 0x2b, 0xd6, 0x4b, 0xcd, 0x86, 0x9b, 0x33, 0xaa, 0xdb, 0xc9, 0x3c, 0xb6, 0x55, 0x0f, 0x6e,
	0x65, 0x5f, 0xb5, 0xec, 0xf9, 0xb4, 0xba, 0xad, 0x81, 0xfb, 0x42, 0xf6, 0x55, 0x67, 0x4d, 0xea,
	0xbc, 0x99, 0xd6, 0xb1, 0x54, 0x3d, 0xf0, 0x61, 0xc4, 0x06, 0x7e, 0x48, 0x23, 0x04, 0xed, 0x33,
	0xd0, 0x28, 0xfa, 0x82, 0x51, 0x84, 0x72, 0xa1, 0x66, 0xd6, 0x4b, 0x4d, 0x37, 0xb7, 0xf5, 0x2e,
	0x89, 0x5d, 0xad, 0x52, 0x2d, 0x67, 0x3e, 0xad, 0xee, 0xac, 0xbc, 0x0b, 0x61, 0xe7, 0x70, 0x71,
	0xbf, 0x1e, 0xb1, 0xc1, 0x06, 0xee, 0xa0, 0x75, 0x20, 0xd4, 0x5f, 0xed, 0xc5, 0x7f, 0xb5, 0xef,
	0xce, 0xa7, 0x55, 0x5b, 0xa8, 0x4c, 0xf7, 0x9e, 0x50, 0x9b, 0x58, 0x30, 0xfe, 0x26, 0xc6, 0x47,
	0x4c, 0xcc, 0x71, 0x4c, 0xcc, 0x49, 0x4c, 0xcc, 0xaf, 0x98, 0x98, 0xef, 0x33, 0x62, 0x4c, 0x66,
	0xc4, 0xf8, 0x9c, 0x11, 0xe3, 0xfe, 0x92, 0x0b, 0x1c, 0x3c, 0x05, 0x2e, 0x53, 0xa1, 0x07, 0x52,
	0xf0, 0x90, 0x86, 0x43, 0xe6, 0x75, 0x93, 0x61, 0xda, 0x80, 0x2f, 0x4a, 0x3f, 0x78, 0xa3, 0xf5,
	0xc5, 0x0a, 0x89, 0xa0, 0x25, 0x7d, 0x4c, 0xbf, 0x40, 0xb0, 0x95, 0x2c, 0xf7, 0xe2, 0x37, 0x00,
	0x00, 0xff, 0xff, 0xae, 0xa0, 0xc9, 0xb4, 0x8c, 0x02, 0x00, 0x00,
}

func (this *GenesisState) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GenesisState)
	if !ok {
		that2, ok := that.(GenesisState)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Registration) != len(that1.Registration) {
		return false
	}
	for i := range this.Registration {
		if !this.Registration[i].Equal(that1.Registration[i]) {
			return false
		}
	}
	if !this.NodeExchMasterCertificate.Equal(that1.NodeExchMasterCertificate) {
		return false
	}
	if !this.IoMasterCertificate.Equal(that1.IoMasterCertificate) {
		return false
	}
	return true
}
func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IoMasterCertificate != nil {
		{
			size, err := m.IoMasterCertificate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.NodeExchMasterCertificate != nil {
		{
			size, err := m.NodeExchMasterCertificate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Registration) > 0 {
		for iNdEx := len(m.Registration) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Registration[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Registration) > 0 {
		for _, e := range m.Registration {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.NodeExchMasterCertificate != nil {
		l = m.NodeExchMasterCertificate.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.IoMasterCertificate != nil {
		l = m.IoMasterCertificate.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Registration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Registration = append(m.Registration, &RegistrationNodeInfo{})
			if err := m.Registration[len(m.Registration)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeExchMasterCertificate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.NodeExchMasterCertificate == nil {
				m.NodeExchMasterCertificate = &MasterCertificate{}
			}
			if err := m.NodeExchMasterCertificate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IoMasterCertificate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.IoMasterCertificate == nil {
				m.IoMasterCertificate = &MasterCertificate{}
			}
			if err := m.IoMasterCertificate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
