// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: secret/tss/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is the request type for the Query/Params RPC method
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56bfe6200bd164ea, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is the response type for the Query/Params RPC method
type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56bfe6200bd164ea, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryKeySetRequest is the request type for the Query/KeySet RPC method
type QueryKeySetRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryKeySetRequest) Reset()         { *m = QueryKeySetRequest{} }
func (m *QueryKeySetRequest) String() string { return proto.CompactTextString(m) }
func (*QueryKeySetRequest) ProtoMessage()    {}
func (*QueryKeySetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56bfe6200bd164ea, []int{2}
}
func (m *QueryKeySetRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryKeySetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryKeySetRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryKeySetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryKeySetRequest.Merge(m, src)
}
func (m *QueryKeySetRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryKeySetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryKeySetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryKeySetRequest proto.InternalMessageInfo

func (m *QueryKeySetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// QueryKeySetResponse is the response type for the Query/KeySet RPC method
type QueryKeySetResponse struct {
	KeySet KeySet `protobuf:"bytes,1,opt,name=key_set,json=keySet,proto3" json:"key_set"`
}

func (m *QueryKeySetResponse) Reset()         { *m = QueryKeySetResponse{} }
func (m *QueryKeySetResponse) String() string { return proto.CompactTextString(m) }
func (*QueryKeySetResponse) ProtoMessage()    {}
func (*QueryKeySetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56bfe6200bd164ea, []int{3}
}
func (m *QueryKeySetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryKeySetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryKeySetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryKeySetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryKeySetResponse.Merge(m, src)
}
func (m *QueryKeySetResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryKeySetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryKeySetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryKeySetResponse proto.InternalMessageInfo

func (m *QueryKeySetResponse) GetKeySet() KeySet {
	if m != nil {
		return m.KeySet
	}
	return KeySet{}
}

// QueryAllKeySetsRequest is the request type for the Query/AllKeySets RPC method
type QueryAllKeySetsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllKeySetsRequest) Reset()         { *m = QueryAllKeySetsRequest{} }
func (m *QueryAllKeySetsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllKeySetsRequest) ProtoMessage()    {}
func (*QueryAllKeySetsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56bfe6200bd164ea, []int{4}
}
func (m *QueryAllKeySetsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllKeySetsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllKeySetsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllKeySetsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllKeySetsRequest.Merge(m, src)
}
func (m *QueryAllKeySetsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllKeySetsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllKeySetsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllKeySetsRequest proto.InternalMessageInfo

func (m *QueryAllKeySetsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryAllKeySetsResponse is the response type for the Query/AllKeySets RPC method
type QueryAllKeySetsResponse struct {
	KeySets    []KeySet            `protobuf:"bytes,1,rep,name=key_sets,json=keySets,proto3" json:"key_sets"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllKeySetsResponse) Reset()         { *m = QueryAllKeySetsResponse{} }
func (m *QueryAllKeySetsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllKeySetsResponse) ProtoMessage()    {}
func (*QueryAllKeySetsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56bfe6200bd164ea, []int{5}
}
func (m *QueryAllKeySetsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllKeySetsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllKeySetsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllKeySetsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllKeySetsResponse.Merge(m, src)
}
func (m *QueryAllKeySetsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllKeySetsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllKeySetsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllKeySetsResponse proto.InternalMessageInfo

func (m *QueryAllKeySetsResponse) GetKeySets() []KeySet {
	if m != nil {
		return m.KeySets
	}
	return nil
}

func (m *QueryAllKeySetsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryDKGSessionRequest is the request type for the Query/DKGSession RPC method
type QueryDKGSessionRequest struct {
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (m *QueryDKGSessionRequest) Reset()         { *m = QueryDKGSessionRequest{} }
func (m *QueryDKGSessionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDKGSessionRequest) ProtoMessage()    {}
func (*QueryDKGSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56bfe6200bd164ea, []int{6}
}
func (m *QueryDKGSessionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDKGSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDKGSessionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDKGSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDKGSessionRequest.Merge(m, src)
}
func (m *QueryDKGSessionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDKGSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDKGSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDKGSessionRequest proto.InternalMessageInfo

func (m *QueryDKGSessionRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

// QueryDKGSessionResponse is the response type for the Query/DKGSession RPC method
type QueryDKGSessionResponse struct {
	Session DKGSession `protobuf:"bytes,1,opt,name=session,proto3" json:"session"`
}

func (m *QueryDKGSessionResponse) Reset()         { *m = QueryDKGSessionResponse{} }
func (m *QueryDKGSessionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDKGSessionResponse) ProtoMessage()    {}
func (*QueryDKGSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56bfe6200bd164ea, []int{7}
}
func (m *QueryDKGSessionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDKGSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDKGSessionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDKGSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDKGSessionResponse.Merge(m, src)
}
func (m *QueryDKGSessionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDKGSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDKGSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDKGSessionResponse proto.InternalMessageInfo

func (m *QueryDKGSessionResponse) GetSession() DKGSession {
	if m != nil {
		return m.Session
	}
	return DKGSession{}
}

// QueryAllDKGSessionsRequest is the request type for the Query/AllDKGSessions RPC method
type QueryAllDKGSessionsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllDKGSessionsRequest) Reset()         { *m = QueryAllDKGSessionsRequest{} }
func (m *QueryAllDKGSessionsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllDKGSessionsRequest) ProtoMessage()    {}
func (*QueryAllDKGSessionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56bfe6200bd164ea, []int{8}
}
func (m *QueryAllDKGSessionsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllDKGSessionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllDKGSessionsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllDKGSessionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllDKGSessionsRequest.Merge(m, src)
}
func (m *QueryAllDKGSessionsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllDKGSessionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllDKGSessionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllDKGSessionsRequest proto.InternalMessageInfo

func (m *QueryAllDKGSessionsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryAllDKGSessionsResponse is the response type for the Query/AllDKGSessions RPC method
type QueryAllDKGSessionsResponse struct {
	Sessions   []DKGSession        `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllDKGSessionsResponse) Reset()         { *m = QueryAllDKGSessionsResponse{} }
func (m *QueryAllDKGSessionsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllDKGSessionsResponse) ProtoMessage()    {}
func (*QueryAllDKGSessionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56bfe6200bd164ea, []int{9}
}
func (m *QueryAllDKGSessionsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllDKGSessionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllDKGSessionsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllDKGSessionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllDKGSessionsResponse.Merge(m, src)
}
func (m *QueryAllDKGSessionsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllDKGSessionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllDKGSessionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllDKGSessionsResponse proto.InternalMessageInfo

func (m *QueryAllDKGSessionsResponse) GetSessions() []DKGSession {
	if m != nil {
		return m.Sessions
	}
	return nil
}

func (m *QueryAllDKGSessionsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QuerySigningRequestRequest is the request type for the Query/SigningRequest RPC method
type QuerySigningRequestRequest struct {
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (m *QuerySigningRequestRequest) Reset()         { *m = QuerySigningRequestRequest{} }
func (m *QuerySigningRequestRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySigningRequestRequest) ProtoMessage()    {}
func (*QuerySigningRequestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56bfe6200bd164ea, []int{10}
}
func (m *QuerySigningRequestRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySigningRequestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySigningRequestRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySigningRequestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySigningRequestRequest.Merge(m, src)
}
func (m *QuerySigningRequestRequest) XXX_Size() int {
	return m.Size()
}
func (m *QuerySigningRequestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySigningRequestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySigningRequestRequest proto.InternalMessageInfo

func (m *QuerySigningRequestRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

// QuerySigningRequestResponse is the response type for the Query/SigningRequest RPC method
type QuerySigningRequestResponse struct {
	Request SigningRequest `protobuf:"bytes,1,opt,name=request,proto3" json:"request"`
}

func (m *QuerySigningRequestResponse) Reset()         { *m = QuerySigningRequestResponse{} }
func (m *QuerySigningRequestResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySigningRequestResponse) ProtoMessage()    {}
func (*QuerySigningRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56bfe6200bd164ea, []int{11}
}
func (m *QuerySigningRequestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySigningRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySigningRequestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySigningRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySigningRequestResponse.Merge(m, src)
}
func (m *QuerySigningRequestResponse) XXX_Size() int {
	return m.Size()
}
func (m *QuerySigningRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySigningRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySigningRequestResponse proto.InternalMessageInfo

func (m *QuerySigningRequestResponse) GetRequest() SigningRequest {
	if m != nil {
		return m.Request
	}
	return SigningRequest{}
}

// QueryAllSigningRequestsRequest is the request type for the Query/AllSigningRequests RPC method
type QueryAllSigningRequestsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllSigningRequestsRequest) Reset()         { *m = QueryAllSigningRequestsRequest{} }
func (m *QueryAllSigningRequestsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllSigningRequestsRequest) ProtoMessage()    {}
func (*QueryAllSigningRequestsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56bfe6200bd164ea, []int{12}
}
func (m *QueryAllSigningRequestsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllSigningRequestsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllSigningRequestsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllSigningRequestsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllSigningRequestsRequest.Merge(m, src)
}
func (m *QueryAllSigningRequestsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllSigningRequestsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllSigningRequestsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllSigningRequestsRequest proto.InternalMessageInfo

func (m *QueryAllSigningRequestsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryAllSigningRequestsResponse is the response type for the Query/AllSigningRequests RPC method
type QueryAllSigningRequestsResponse struct {
	Requests   []SigningRequest    `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllSigningRequestsResponse) Reset()         { *m = QueryAllSigningRequestsResponse{} }
func (m *QueryAllSigningRequestsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllSigningRequestsResponse) ProtoMessage()    {}
func (*QueryAllSigningRequestsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56bfe6200bd164ea, []int{13}
}
func (m *QueryAllSigningRequestsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllSigningRequestsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllSigningRequestsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllSigningRequestsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllSigningRequestsResponse.Merge(m, src)
}
func (m *QueryAllSigningRequestsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllSigningRequestsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllSigningRequestsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllSigningRequestsResponse proto.InternalMessageInfo

func (m *QueryAllSigningRequestsResponse) GetRequests() []SigningRequest {
	if m != nil {
		return m.Requests
	}
	return nil
}

func (m *QueryAllSigningRequestsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "secret.tss.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "secret.tss.v1.QueryParamsResponse")
	proto.RegisterType((*QueryKeySetRequest)(nil), "secret.tss.v1.QueryKeySetRequest")
	proto.RegisterType((*QueryKeySetResponse)(nil), "secret.tss.v1.QueryKeySetResponse")
	proto.RegisterType((*QueryAllKeySetsRequest)(nil), "secret.tss.v1.QueryAllKeySetsRequest")
	proto.RegisterType((*QueryAllKeySetsResponse)(nil), "secret.tss.v1.QueryAllKeySetsResponse")
	proto.RegisterType((*QueryDKGSessionRequest)(nil), "secret.tss.v1.QueryDKGSessionRequest")
	proto.RegisterType((*QueryDKGSessionResponse)(nil), "secret.tss.v1.QueryDKGSessionResponse")
	proto.RegisterType((*QueryAllDKGSessionsRequest)(nil), "secret.tss.v1.QueryAllDKGSessionsRequest")
	proto.RegisterType((*QueryAllDKGSessionsResponse)(nil), "secret.tss.v1.QueryAllDKGSessionsResponse")
	proto.RegisterType((*QuerySigningRequestRequest)(nil), "secret.tss.v1.QuerySigningRequestRequest")
	proto.RegisterType((*QuerySigningRequestResponse)(nil), "secret.tss.v1.QuerySigningRequestResponse")
	proto.RegisterType((*QueryAllSigningRequestsRequest)(nil), "secret.tss.v1.QueryAllSigningRequestsRequest")
	proto.RegisterType((*QueryAllSigningRequestsResponse)(nil), "secret.tss.v1.QueryAllSigningRequestsResponse")
}

func init() { proto.RegisterFile("secret/tss/v1/query.proto", fileDescriptor_56bfe6200bd164ea) }

var fileDescriptor_56bfe6200bd164ea = []byte{
	// 774 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x4f, 0x4f, 0x13, 0x5f,
	0x14, 0xed, 0xf4, 0xf7, 0xb3, 0x85, 0x6b, 0x64, 0xf1, 0xe4, 0xef, 0x08, 0x83, 0x3c, 0x05, 0x14,
	0xc3, 0xbc, 0x14, 0x8c, 0xc6, 0x10, 0x63, 0x24, 0x46, 0x82, 0x24, 0x06, 0x5b, 0x57, 0xc6, 0x04,
	0xa7, 0xed, 0xcb, 0x30, 0x69, 0x99, 0x29, 0x7d, 0x03, 0xda, 0x34, 0x6c, 0xd4, 0x0f, 0x60, 0x82,
	0x2b, 0xb7, 0x2c, 0xfd, 0x22, 0x2c, 0x49, 0xdc, 0xb8, 0x32, 0x06, 0xfc, 0x20, 0xa6, 0xef, 0xdd,
	0x61, 0x98, 0x3f, 0xb5, 0x2c, 0xba, 0x6b, 0xdf, 0x3b, 0xf7, 0x9e, 0x73, 0xee, 0x9d, 0x39, 0x19,
	0x98, 0x10, 0xbc, 0xd2, 0xe4, 0x3e, 0xf3, 0x85, 0x60, 0xfb, 0x05, 0xb6, 0xbb, 0xc7, 0x9b, 0x2d,
	0xb3, 0xd1, 0xf4, 0x7c, 0x8f, 0x5c, 0x53, 0x57, 0xa6, 0x2f, 0x84, 0xb9, 0x5f, 0xd0, 0x87, 0x6d,
	0xcf, 0xf6, 0xe4, 0x0d, 0xeb, 0xfc, 0x52, 0x20, 0x7d, 0xd2, 0xf6, 0x3c, 0xbb, 0xce, 0x99, 0xd5,
	0x70, 0x98, 0xe5, 0xba, 0x9e, 0x6f, 0xf9, 0x8e, 0xe7, 0x0a, 0xbc, 0x8d, 0x75, 0xf7, 0x5b, 0x0d,
	0x1e, 0x5c, 0x2d, 0x54, 0x3c, 0xb1, 0xe3, 0x09, 0x56, 0xb6, 0x04, 0x57, 0xb4, 0x6c, 0xbf, 0x50,
	0xe6, 0xbe, 0x55, 0x60, 0x0d, 0xcb, 0x76, 0x5c, 0xd9, 0x47, 0x61, 0xe9, 0x30, 0x90, 0x57, 0x1d,
	0xc4, 0xa6, 0xd5, 0xb4, 0x76, 0x44, 0x91, 0xef, 0xee, 0x71, 0xe1, 0xd3, 0x17, 0x70, 0x3d, 0x72,
	0x2a, 0x1a, 0x9e, 0x2b, 0x38, 0x59, 0x86, 0x5c, 0x43, 0x9e, 0x8c, 0x6b, 0x37, 0xb5, 0x3b, 0x57,
	0x97, 0x46, 0xcc, 0x88, 0x0f, 0x53, 0xc1, 0x57, 0xff, 0x3f, 0xfe, 0x35, 0x9d, 0x29, 0x22, 0x94,
	0xde, 0x46, 0x86, 0x0d, 0xde, 0x2a, 0x71, 0x1f, 0x19, 0xc8, 0x10, 0x64, 0x9d, 0xaa, 0x6c, 0x33,
	0x58, 0xcc, 0x3a, 0x55, 0xba, 0x81, 0x8c, 0x01, 0x0a, 0x19, 0xef, 0x43, 0xbe, 0xc6, 0x5b, 0x5b,
	0x82, 0xfb, 0x5d, 0x28, 0x15, 0x3e, 0xa0, 0xac, 0xc9, 0x7f, 0xf4, 0x1d, 0x8c, 0xca, 0x66, 0x4f,
	0xeb, 0x75, 0x75, 0x1f, 0x18, 0x23, 0xcf, 0x01, 0xc2, 0x11, 0x60, 0xcb, 0x39, 0x53, 0xcd, 0xcb,
	0xec, 0xcc, 0xcb, 0x54, 0x6b, 0xc2, 0x79, 0x99, 0x9b, 0x96, 0xcd, 0xb1, 0xb6, 0x78, 0xa1, 0x92,
	0x7e, 0xd3, 0x60, 0x2c, 0x41, 0x81, 0x9a, 0x1f, 0xc0, 0x00, 0x6a, 0xee, 0xcc, 0xe9, 0xbf, 0x5e,
	0xa2, 0xf3, 0x4a, 0xb4, 0x20, 0x6b, 0x11, 0x6d, 0x59, 0xa9, 0x6d, 0xbe, 0xa7, 0x36, 0x45, 0x1a,
	0x11, 0xf7, 0x10, 0xed, 0x3f, 0xdb, 0x58, 0x2b, 0x71, 0x21, 0x1c, 0xcf, 0x0d, 0xec, 0x4f, 0x01,
	0x08, 0x75, 0xb2, 0x75, 0x3e, 0xfd, 0x41, 0x3c, 0x59, 0xaf, 0xd2, 0xd7, 0x68, 0xea, 0x62, 0x21,
	0x9a, 0x7a, 0x04, 0x79, 0xc4, 0xe1, 0xd4, 0x26, 0x62, 0x9e, 0xc2, 0x9a, 0xc0, 0x17, 0xe2, 0x69,
	0x15, 0xf4, 0x60, 0x54, 0x21, 0xa8, 0xef, 0x1b, 0x39, 0xd2, 0xe0, 0x46, 0x2a, 0x0d, 0x1a, 0x58,
	0x81, 0x01, 0x14, 0x14, 0x6c, 0xa5, 0xa7, 0x83, 0xf3, 0x82, 0xfe, 0xad, 0x66, 0x05, 0x67, 0x51,
	0x72, 0x6c, 0xd7, 0x71, 0xed, 0xc0, 0x48, 0xb8, 0x9e, 0xa6, 0xfa, 0x79, 0x61, 0x3d, 0x78, 0xb2,
	0x5e, 0xa5, 0x6f, 0xd1, 0x61, 0xbc, 0x18, 0x1d, 0x3e, 0x86, 0x3c, 0x62, 0x71, 0x8c, 0x53, 0x31,
	0x83, 0xd1, 0xba, 0x60, 0x4d, 0x58, 0x43, 0xb7, 0xc1, 0x08, 0xe6, 0x17, 0x05, 0xf6, 0x7d, 0x55,
	0xdf, 0x35, 0x98, 0xee, 0x4a, 0x85, 0x66, 0x9e, 0xc0, 0x00, 0x0a, 0x0b, 0xd6, 0x75, 0x29, 0x37,
	0xe7, 0x45, 0x7d, 0x5b, 0xd9, 0xd2, 0x51, 0x1e, 0xae, 0x48, 0xb5, 0xc4, 0x85, 0x9c, 0x4a, 0x38,
	0x32, 0x13, 0xd3, 0x92, 0x8c, 0x50, 0x9d, 0xfe, 0x0b, 0xa2, 0x68, 0xe8, 0xd4, 0xc7, 0x1f, 0x7f,
	0x0e, 0xb3, 0x63, 0x64, 0x84, 0x45, 0xc3, 0x5c, 0x25, 0x27, 0x11, 0x90, 0x53, 0x49, 0x91, 0xce,
	0x17, 0x09, 0xd4, 0x74, 0xbe, 0x68, 0x9a, 0x52, 0x2a, 0xf9, 0x26, 0x89, 0x1e, 0xe3, 0xab, 0xf1,
	0x96, 0xe0, 0x3e, 0x6b, 0x3b, 0xd5, 0x03, 0xd2, 0x06, 0x08, 0x33, 0x8d, 0xcc, 0xa6, 0x75, 0x4d,
	0xc4, 0xaa, 0x3e, 0xd7, 0x0b, 0x86, 0x02, 0x0c, 0x29, 0x60, 0x9c, 0x8c, 0xa6, 0x0a, 0x10, 0xe4,
	0xb3, 0x06, 0x10, 0xbe, 0x86, 0xe9, 0xec, 0x89, 0x54, 0x4b, 0x67, 0x4f, 0x66, 0x18, 0x9d, 0x97,
	0xec, 0x33, 0x64, 0x3a, 0xc6, 0x5e, 0xad, 0xd9, 0xac, 0x1d, 0xe6, 0xe2, 0x01, 0xf9, 0xa4, 0xc1,
	0x50, 0x34, 0x46, 0xc8, 0xdd, 0x2e, 0x0e, 0x93, 0x89, 0xa6, 0x2f, 0x5c, 0x06, 0x8a, 0x92, 0x74,
	0x29, 0x69, 0x98, 0x90, 0xa4, 0x24, 0xf2, 0x55, 0x83, 0xa1, 0xe8, 0x43, 0x9e, 0xae, 0x22, 0x35,
	0x4b, 0xd2, 0x55, 0xa4, 0x27, 0x07, 0xbd, 0x27, 0x55, 0xcc, 0x92, 0x5b, 0x31, 0x15, 0x42, 0xc1,
	0x59, 0x3b, 0x4c, 0xa5, 0x03, 0x72, 0xa8, 0x01, 0x49, 0xbe, 0xb8, 0x64, 0xb1, 0x8b, 0xeb, 0xf4,
	0x2c, 0xd1, 0xcd, 0xcb, 0xc2, 0x7b, 0x3c, 0x39, 0x28, 0x71, 0x75, 0xed, 0xf8, 0xd4, 0xd0, 0x4e,
	0x4e, 0x0d, 0xed, 0xf7, 0xa9, 0xa1, 0x7d, 0x39, 0x33, 0x32, 0x27, 0x67, 0x46, 0xe6, 0xe7, 0x99,
	0x91, 0x79, 0xb3, 0x68, 0x3b, 0xfe, 0xf6, 0x5e, 0xd9, 0xac, 0x78, 0x3b, 0x4c, 0x54, 0x9a, 0x7e,
	0xdd, 0x2a, 0x0b, 0x56, 0x92, 0x4d, 0x5e, 0x72, 0xff, 0xbd, 0xd7, 0xac, 0xb1, 0x0f, 0xb2, 0x9b,
	0xfc, 0x84, 0x2a, 0xe7, 0xe4, 0x77, 0xd1, 0xf2, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x76,
	0xd9, 0xdd, 0xbe, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params queries module parameters
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// KeySet queries a KeySet by ID
	KeySet(ctx context.Context, in *QueryKeySetRequest, opts ...grpc.CallOption) (*QueryKeySetResponse, error)
	// AllKeySets queries all KeySets
	AllKeySets(ctx context.Context, in *QueryAllKeySetsRequest, opts ...grpc.CallOption) (*QueryAllKeySetsResponse, error)
	// DKGSession queries a DKG session by ID
	DKGSession(ctx context.Context, in *QueryDKGSessionRequest, opts ...grpc.CallOption) (*QueryDKGSessionResponse, error)
	// AllDKGSessions queries all DKG sessions
	AllDKGSessions(ctx context.Context, in *QueryAllDKGSessionsRequest, opts ...grpc.CallOption) (*QueryAllDKGSessionsResponse, error)
	// SigningRequest queries a signing request by ID
	SigningRequest(ctx context.Context, in *QuerySigningRequestRequest, opts ...grpc.CallOption) (*QuerySigningRequestResponse, error)
	// AllSigningRequests queries all signing requests
	AllSigningRequests(ctx context.Context, in *QueryAllSigningRequestsRequest, opts ...grpc.CallOption) (*QueryAllSigningRequestsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/secret.tss.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) KeySet(ctx context.Context, in *QueryKeySetRequest, opts ...grpc.CallOption) (*QueryKeySetResponse, error) {
	out := new(QueryKeySetResponse)
	err := c.cc.Invoke(ctx, "/secret.tss.v1.Query/KeySet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllKeySets(ctx context.Context, in *QueryAllKeySetsRequest, opts ...grpc.CallOption) (*QueryAllKeySetsResponse, error) {
	out := new(QueryAllKeySetsResponse)
	err := c.cc.Invoke(ctx, "/secret.tss.v1.Query/AllKeySets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DKGSession(ctx context.Context, in *QueryDKGSessionRequest, opts ...grpc.CallOption) (*QueryDKGSessionResponse, error) {
	out := new(QueryDKGSessionResponse)
	err := c.cc.Invoke(ctx, "/secret.tss.v1.Query/DKGSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllDKGSessions(ctx context.Context, in *QueryAllDKGSessionsRequest, opts ...grpc.CallOption) (*QueryAllDKGSessionsResponse, error) {
	out := new(QueryAllDKGSessionsResponse)
	err := c.cc.Invoke(ctx, "/secret.tss.v1.Query/AllDKGSessions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SigningRequest(ctx context.Context, in *QuerySigningRequestRequest, opts ...grpc.CallOption) (*QuerySigningRequestResponse, error) {
	out := new(QuerySigningRequestResponse)
	err := c.cc.Invoke(ctx, "/secret.tss.v1.Query/SigningRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllSigningRequests(ctx context.Context, in *QueryAllSigningRequestsRequest, opts ...grpc.CallOption) (*QueryAllSigningRequestsResponse, error) {
	out := new(QueryAllSigningRequestsResponse)
	err := c.cc.Invoke(ctx, "/secret.tss.v1.Query/AllSigningRequests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params queries module parameters
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// KeySet queries a KeySet by ID
	KeySet(context.Context, *QueryKeySetRequest) (*QueryKeySetResponse, error)
	// AllKeySets queries all KeySets
	AllKeySets(context.Context, *QueryAllKeySetsRequest) (*QueryAllKeySetsResponse, error)
	// DKGSession queries a DKG session by ID
	DKGSession(context.Context, *QueryDKGSessionRequest) (*QueryDKGSessionResponse, error)
	// AllDKGSessions queries all DKG sessions
	AllDKGSessions(context.Context, *QueryAllDKGSessionsRequest) (*QueryAllDKGSessionsResponse, error)
	// SigningRequest queries a signing request by ID
	SigningRequest(context.Context, *QuerySigningRequestRequest) (*QuerySigningRequestResponse, error)
	// AllSigningRequests queries all signing requests
	AllSigningRequests(context.Context, *QueryAllSigningRequestsRequest) (*QueryAllSigningRequestsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) KeySet(ctx context.Context, req *QueryKeySetRequest) (*QueryKeySetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeySet not implemented")
}
func (*UnimplementedQueryServer) AllKeySets(ctx context.Context, req *QueryAllKeySetsRequest) (*QueryAllKeySetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllKeySets not implemented")
}
func (*UnimplementedQueryServer) DKGSession(ctx context.Context, req *QueryDKGSessionRequest) (*QueryDKGSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DKGSession not implemented")
}
func (*UnimplementedQueryServer) AllDKGSessions(ctx context.Context, req *QueryAllDKGSessionsRequest) (*QueryAllDKGSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllDKGSessions not implemented")
}
func (*UnimplementedQueryServer) SigningRequest(ctx context.Context, req *QuerySigningRequestRequest) (*QuerySigningRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SigningRequest not implemented")
}
func (*UnimplementedQueryServer) AllSigningRequests(ctx context.Context, req *QueryAllSigningRequestsRequest) (*QueryAllSigningRequestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllSigningRequests not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/secret.tss.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_KeySet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryKeySetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).KeySet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/secret.tss.v1.Query/KeySet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).KeySet(ctx, req.(*QueryKeySetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllKeySets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllKeySetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllKeySets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/secret.tss.v1.Query/AllKeySets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllKeySets(ctx, req.(*QueryAllKeySetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DKGSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDKGSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DKGSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/secret.tss.v1.Query/DKGSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DKGSession(ctx, req.(*QueryDKGSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllDKGSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllDKGSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllDKGSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/secret.tss.v1.Query/AllDKGSessions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllDKGSessions(ctx, req.(*QueryAllDKGSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SigningRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySigningRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SigningRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/secret.tss.v1.Query/SigningRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SigningRequest(ctx, req.(*QuerySigningRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllSigningRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllSigningRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllSigningRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/secret.tss.v1.Query/AllSigningRequests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllSigningRequests(ctx, req.(*QueryAllSigningRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "secret.tss.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "KeySet",
			Handler:    _Query_KeySet_Handler,
		},
		{
			MethodName: "AllKeySets",
			Handler:    _Query_AllKeySets_Handler,
		},
		{
			MethodName: "DKGSession",
			Handler:    _Query_DKGSession_Handler,
		},
		{
			MethodName: "AllDKGSessions",
			Handler:    _Query_AllDKGSessions_Handler,
		},
		{
			MethodName: "SigningRequest",
			Handler:    _Query_SigningRequest_Handler,
		},
		{
			MethodName: "AllSigningRequests",
			Handler:    _Query_AllSigningRequests_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "secret/tss/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryKeySetRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryKeySetRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryKeySetRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryKeySetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryKeySetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryKeySetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.KeySet.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllKeySetsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllKeySetsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllKeySetsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllKeySetsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllKeySetsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllKeySetsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.KeySets) > 0 {
		for iNdEx := len(m.KeySets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.KeySets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryDKGSessionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDKGSessionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDKGSessionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SessionId) > 0 {
		i -= len(m.SessionId)
		copy(dAtA[i:], m.SessionId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.SessionId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDKGSessionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDKGSessionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDKGSessionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Session.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllDKGSessionsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllDKGSessionsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllDKGSessionsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllDKGSessionsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllDKGSessionsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllDKGSessionsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sessions) > 0 {
		for iNdEx := len(m.Sessions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Sessions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QuerySigningRequestRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySigningRequestRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySigningRequestRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RequestId) > 0 {
		i -= len(m.RequestId)
		copy(dAtA[i:], m.RequestId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.RequestId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QuerySigningRequestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySigningRequestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySigningRequestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Request.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllSigningRequestsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllSigningRequestsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllSigningRequestsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllSigningRequestsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllSigningRequestsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllSigningRequestsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Requests) > 0 {
		for iNdEx := len(m.Requests) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Requests[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryKeySetRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryKeySetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.KeySet.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllKeySetsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllKeySetsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.KeySets) > 0 {
		for _, e := range m.KeySets {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDKGSessionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SessionId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDKGSessionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Session.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllDKGSessionsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllDKGSessionsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Sessions) > 0 {
		for _, e := range m.Sessions {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QuerySigningRequestRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RequestId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QuerySigningRequestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Request.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllSigningRequestsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllSigningRequestsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Requests) > 0 {
		for _, e := range m.Requests {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryKeySetRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryKeySetRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryKeySetRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryKeySetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryKeySetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryKeySetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeySet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.KeySet.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllKeySetsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllKeySetsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllKeySetsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllKeySetsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllKeySetsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllKeySetsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeySets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KeySets = append(m.KeySets, KeySet{})
			if err := m.KeySets[len(m.KeySets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDKGSessionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDKGSessionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDKGSessionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SessionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDKGSessionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDKGSessionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDKGSessionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Session", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Session.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllDKGSessionsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllDKGSessionsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllDKGSessionsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllDKGSessionsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllDKGSessionsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllDKGSessionsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sessions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sessions = append(m.Sessions, DKGSession{})
			if err := m.Sessions[len(m.Sessions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySigningRequestRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySigningRequestRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySigningRequestRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySigningRequestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySigningRequestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySigningRequestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Request", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Request.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllSigningRequestsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllSigningRequestsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllSigningRequestsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllSigningRequestsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllSigningRequestsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllSigningRequestsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Requests", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Requests = append(m.Requests, SigningRequest{})
			if err := m.Requests[len(m.Requests)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
