#!/bin/bash
# This `DEBIAN/postinst` script is run post-installation

set -e

cat <<EOF > /etc/systemd/system/enigma-node.service
[Unit]
Description=Enigma node service
After=network.target

[Service]
Type=simple
ExecStart=$(which enigmad) start --pruning nothing
User=XXXXX
Restart=always
StartLimitInterval=0

[Install]
WantedBy=multi-user.target
EOF

sudo perl -i -pe 's/#SystemMaxUse=.*/SystemMaxUse=50M/' /etc/systemd/journald.conf || true
sudo systemctl reload systemd-journald || true

echo "Before you launce your node make sure to edit the User=XXXXX in /etc/systemd/system/enigma-node.service"
echo 'E.g. sudo perl -i -pe "s/XXXXX/$USER/" /etc/systemd/system/enigma-node.service'